## **Kenya Regional Crop Yield Prediction Using Machine Learning**

### Background (Business Understanding)

Agriculture is one of the leading economic drivers in Kenya. According to the World Bank [^1], the sector contributes **20% - 30% of the total national Gross Domestic Product (GDP)**. This means that agriculture significantly tips the economic balance in terms of value added to the economy through **employment, food security, and poverty reduction**.  

While agriculture as a whole has huge significance for the economy, it is vital to understand that the **crop farming sub-sector contributes approximately 15% to the entire national GDP**[^2] . This highlights the specific impact of crop farming within the broader agricultural sector.

It is the leading subsector in agriculture followed by livestock farming,forestry and finally fishing.  Therefore crop farming is one of the key indirect drivers of the economy. Resent publiction [^3],  crop farming is directly tied to the fast economic growth via agricuture in first quater of 2025. This underpins the fact that high crop yield coinsides with higher economic growth. 

Therefore the possiblities that would appear as a result of predicting crop yields are quite endless, the following are just afew solutions that would be possible by predicting crop yields in Kenya ;

1. Provide farm level intelligence to farmers in terms of crop variety with possible highest yield
2. National food security informed decision making in form of early warning for poor harvest season
3. Help inform economic policies such as when to provide subbsidies to farmers 
4. Assist iin better storage and logistic preparation
5. The model can help power a digital agricultural product such as Mobile advisory app for farmers.

#### References

[^1]: World Bank. "Kenya Economic Update: Transforming Agricultural Productivity to Achieve Food Security for All." Available at: [https://www.worldbank.org/en/country/kenya/publication/kenya-economic-update-transforming-agricultural-productivity-to-achieve-food-security-for-all]

[^2]: Africa Check. "How much does agriculture contribute to Kenya’s GDP?" (2024). Available at: [https://africacheck.org/infofinder/explore-facts/how-much-does-agriculture-contribute-kenyas-gdp]

[^3]: "Kenya's economy grows 4.9% in first quarter of 2025"  [https://www.reuters.com/world/africa/kenyas-gdp-growth-49-year-on-year-first-quarter-2025-2025-07-03]

### Problem Statement

Crop yield is influenced by multiple factors such as climate variability, regional agro-ecological conditions, crop type and management practices, which makes accurate forecast of crop yield a complex task.  Traditional and intuitive methods cannot keep up with the complexity and often result in inconsistece and uncertainity. However adnces in machine learnig and data scince privide an oppotunity to transform historical records into actionable yield forecast wchich can support evidence based decision making.  
The task in this notebook is to develop a machine learning model that is capable of predicting yield of different types of crop  in different regions of Kenya based on historical data of the factors that possibly influnce amount of crop yield at a given time

#### Objectives

1. What are the principle factors affecting crop yield ?
2. What crops are available  ?
3. Which are the most staple crops?
4. How are the  crops distributed ?

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import glob
import matplotlib.pyplot as plt 
import os

In [2]:
# Machine learning libraries
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pickle

In [3]:
DATA_PATH = r"C:\Users\O M E N\Documents\Data-science\capstone project\datasets"
crop_df_1 = pd.read_csv(os.path.join(DATA_PATH, "crop_data.csv"))
crop_df_1.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\O M E N\\Documents\\Data-science\\capstone project\\datasets\\crop_data.csv'

In [ ]:
crop_df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53832 entries, 0 to 53831
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 53832 non-null  object
 1   source_organization     53832 non-null  object
 2   source_document         53832 non-null  object
 3   datasourcedocument      53832 non-null  int64
 4   fnid                    53832 non-null  object
 5   admin_0                 53832 non-null  object
 6   admin_1                 53832 non-null  object
 7   admin_2                 53832 non-null  object
 8   admin_3                 0 non-null      float64
 9   admin_4                 0 non-null      float64
 10  population_group        0 non-null      float64
 11  crop_production_system  53832 non-null  object
 12  start_date              53832 non-null  object
 13  period_date             53832 non-null  object
 14  season_name             53832 non-null  object
 15  season_type             53832 non-null  object
 16  indicator               53832 non-null  object
 17  value                   38319 non-null  float64
 18  population              36316 non-null  float64
 19  value_per_capita        26434 non-null  float64
 20  product                 53832 non-null  object
 21  unit                    53832 non-null  object
 22  unit_name               53832 non-null  object
 23  cpcv2                   53832 non-null  object
 24  cpcv2_description       53832 non-null  object
 25  geographic_group        53832 non-null  object
 26  fewsnet_region          53832 non-null  object
 27  country_code            53832 non-null  object
 28  collection_schedule     53832 non-null  object
 29  collection_date         53832 non-null  object
 30  season_date             53832 non-null  object
 31  season_year             53832 non-null  object
 32  status                  53832 non-null  object
 33  collection_status       53832 non-null  object
 34  publication_name        53832 non-null  object
 35  document_type           53832 non-null  object
 36  id                      53832 non-null  int64
 37  dataseries_name         53832 non-null  object
dtypes: float64(6), int64(2), object(30)
memory usage: 15.6+ MB

In [ ]:
crop_df_2 = pd.read_excel(os.path.join(DATA_PATH, "Kenyas_Agricultural_Production.xlsx"))
crop_df_2.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,QCL,Crops and livestock products,404,Kenya,5510,Production,1929.07,"Abaca, manila hemp, raw",1976,1976,tonnes,10.0,E,Estimated value
1,QCL,Crops and livestock products,404,Kenya,5510,Production,1929.07,"Abaca, manila hemp, raw",1977,1977,tonnes,10.0,E,Estimated value
2,QCL,Crops and livestock products,404,Kenya,5510,Production,1929.07,"Abaca, manila hemp, raw",1978,1978,tonnes,10.0,E,Estimated value
3,QCL,Crops and livestock products,404,Kenya,5510,Production,1929.07,"Abaca, manila hemp, raw",1979,1979,tonnes,10.0,E,Estimated value
4,QCL,Crops and livestock products,404,Kenya,5510,Production,1929.07,"Abaca, manila hemp, raw",1980,1980,tonnes,10.0,E,Estimated value

In [ ]:
crop_df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18182 entries, 0 to 18181
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       18182 non-null  object
 1   Domain            18182 non-null  object
 2   Area Code (M49)   18182 non-null  int64
 3   Area              18182 non-null  object
 4   Element Code      18182 non-null  int64
 5   Element           18182 non-null  object
 6   Item Code (CPC)   18182 non-null  object
 7   Item              18182 non-null  object
 8   Year Code         18182 non-null  int64
 9   Year              18182 non-null  int64
 10  Unit              18182 non-null  object
 11  Value             18182 non-null  float64
 12  Flag              18182 non-null  object
 13  Flag Description  18182 non-null  object
dtypes: float64(1), int64(4), object(9)
memory usage: 1.9+ MB

In [ ]:
crop_df_3 = pd.read_csv(os.path.join(DATA_PATH, "kenya_crops_only.csv"))
crop_df_3.head()

,Year,Item,Item Code (CPC),Area_Harvested_ha,Production_tonnes,Yield_hg_per_ha
0,1961,Apricots,1343.0,2.0,10.0,50000.0
1,1961,Avocados,1311.0,1100.0,16000.0,145455.0
2,1961,Bananas,1312.0,40000.0,400000.0,100000.0
3,1961,Barley,115.0,12666.0,13513.0,10669.0
4,1961,"Beans, dry",1701.0,115000.0,55000.0,4783.0

In [ ]:
crop_df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3658 entries, 0 to 3657
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               3658 non-null   int64
 1   Item               3658 non-null   object
 2   Item Code (CPC)    3658 non-null   float64
 3   Area_Harvested_ha  3377 non-null   float64
 4   Production_tonnes  3658 non-null   float64
 5   Yield_hg_per_ha    3317 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 171.6+ KB

In [ ]:
rainfall_df = pd.read_csv(os.path.join(DATA_PATH, "kenya-climate-rainfall-mm.csv"))
rainfall_df.head()

   Year Month Average  Rainfall - (MM)
0  1991   Jan Average          38.2847
1  1991   Feb Average          12.7492
2  1991   Mar Average          73.3656
3  1991   Apr Average          83.1350
4  1991   May Average         112.2750

In [ ]:
rainfall_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             312 non-null    int64
 1   Month Average    312 non-null    object
 2   Rainfall - (MM)  312 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 7.4+ KB

In [ ]:
temperature_df = pd.read_csv(os.path.join(DATA_PATH, "kenya-climate-temp.csv"))
temperature_df.head()

   Year Month Average  Temperature - (Celsius)
0  1991   Jan Average                  25.1631
1  1991   Feb Average                  26.0839
2  1991   Mar Average                  26.2236
3  1991   Apr Average                  25.5812
4  1991   May Average                  24.6618

In [ ]:
temperature_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     312 non-null    int64
 1   Month Average            312 non-null    object
 2   Temperature - (Celsius)  312 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 7.4+ KB

In [ ]:
crop_df_1.columns

Index(['country', 'source_organization', 'source_document',
       'datasourcedocument', 'fnid', 'admin_0', 'admin_1', 'admin_2',
       'admin_3', 'admin_4', 'population_group', 'crop_production_system',
       'start_date', 'period_date', 'season_name', 'season_type', 'indicator',
       'value', 'population', 'value_per_capita', 'product', 'unit',
       'unit_name', 'cpcv2', 'cpcv2_description', 'geographic_group',
       'fewsnet_region', 'country_code', 'collection_schedule',
       'collection_date', 'season_date', 'season_year', 'status',
       'collection_status', 'publication_name', 'document_type', 'id',
       'dataseries_name'],
      dtype='object')